### PR TITLE
Add footprints for the WS2812 LED family

### PR DESCRIPTION
**Pull request by yaqwsx**
I have added all "smart" LEDs manufactured by Worldsemi, this PR adds their footprints.

The footprints are PLCC4/6 (the same as in 5050 LED), however the manufacture has a different pin numbering, so I marked these footprints with the name of the part and kept the same numbering as the datasheet uses (to avoid confusion).

### CODE REVIEW

**Comment by yaqwsx** [comment]
Description of the packages added

**Comment by ricardocrudo** [comment]
I'd like to suggest you to rename them to:
LED_PLCC4-WS2812B.kicad_mod -> LED_WS2812B-PLCC4.kicad_mod
LED_PLCC6-WS2812.kicad_mod -> LED_WS2812-PLCC6.kicad_mod
Also the courtyard lines is supposed to wrap the component body.
Thanks

**Comment by yaqwsx** [comment]
Thank you for the feedback. I renamed the footprints and changed their names (with 3D models in PR for Kicad-library)

**Comment by pointhi** [comment]
Please look onto KLC Rule 6.7 in detail:
```
6.7.  Courtyard clearance is 0.25mm except for components smaller than 0603 at 0.15mm, connectors, SMD canned capacitors and crystals at 0.5mm and BGA at 1.0mm. (IPC-7251, IPC-7351B)
```

In other words: you could move the silkscreen more to the inside (as long as it is still visible), but the courtjard has to have a clearance of 0.25mm from the edges of the footprint and the edges of the component.

**Comment by yaqwsx** [comment]
Fixed, I hope the footprints are allright now.

**Comment by yaqwsx** [comment]
Is there any problem with the footprints?

**Comment by yaqwsx** [comment]
Is there any problem with the footprints?

**Comment by diggit** [comment]
Can you look at this @pointhi ? Your last note was probably resolved.

**Comment by pointhi** [comment]
thanks for your contribution.

@diggit I think you can simply merge such PR, when the outstanding issues are solved and you find no other ones.

**Comment by diggit** [comment]
@pointhi I don't have this repo forked and cloned for testing and I am not so familiar with KLC rules for footprints yet. Thanks, for resolving.

**Comment by pointhi** [comment]
When It helps, here a simple tutorial how you can get the repo quickly:

1. open ```view command line instructions``` at the end of the PR (only visible when the PR is not merged yet)
2. You should see a line like:

 ```git pull https://github.com/username/repo.pretty.git patch-1```

3. go with the commandline into a dir which you use for checking and enter the slightly changed command (don't forget the ```-b``` for the remote branche):

 ```git clone https://github.com/username/repo.pretty.git -b patch-1```

4. Now you should have a directory with the repo name, and all applied patches of the user in it

**Comment by CarlPoirier** [comment]
@diggit @pointhi Even better yet, just copy the Github URL and in the
Footprint Libraries Manager from Pcbnew, paste it in a project-specific
fp-lib-table.

On Sun, Mar 13, 2016 at 6:47 PM, Thomas Pointhuber <notifications@github.com

**Comment by CarlPoirier** [comment]
Then if everything is fine, you merge from here using the big green button
;)

**Pull request merged**
