### PR TITLE
Update Cree LED footprints

### PR DESCRIPTION
**Pull request by evanshultz**
Changes:
- Add ref des text to F.Fab
- Add 3D model link (though none are present in the 3D repo, I believe)
- Place ref des above and footprint name on below
- Changed "CREE" to "Cree" (see https://github.com/KiCad/LEDs.pretty/issues/38)

Also, on XQ I made the hand soldering variant use the normal XQ 3D model.

I haven't posted the images since there weren't any substantial changes there, mostly just housekeeping.

### CODE REVIEW

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 @poeschlr 
Can someone please check the pad designs? Many of them had violations reported by Travis because of missing a paste layer. But if you look at the datasheet section talking about footprint design, you will see something like this:
image

I believe that means the following
- The "PCB Solder Pad" should be on F.Cu and F.Mask, so that we have copper which is exposed.
- The "Stencil Pattern" section should be only F.Paste, so that the stencil will have openings here.

It appears several of the footprints were not built this way. Many have F.Cu on all pads, which is OK since the Cu will merge together, but some have F.Paste on the Cu pads which would circumvent the desire to have smaller stencil openings. Since it appears many of these footprints were wrong I want to check that I'm correct before going ahead. Please confirm and I'll finish updating these footprints. Thanks!

**Comment by evanshultz** [comment]
This situation isn't addressed in KLC from what I can see. [Section 8](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) gives some info on this topic, but not enough to cover all cases. I think an update is in order? Assuming the above is correct, perhaps something like:
3. Pad layer settings:
   i. Normal copper pads:
      a. Front copper (F.Cu)
      b. Front Mask (F.Mask)
      a. Front paste (F.Paste)
   ii. Copper pads with unique stencil openings:
      a. Front copper (F.Cu)
      b. Front Mask (F.Mask)
   ii. Unique stencil opening layers:
      a. Front paste (F.Paste)

**Comment by SchrodingersGat** [comment]
You have interpreted this correctly. The KLC rule is quite simplistic as often the rule has to be violated to match datasheet specs. Especially when it comes to stencil / soldermask!

**Comment by SchrodingersGat** [comment]
@evanshultz please notify when ready for checking :)

**Comment by evanshultz** [comment]
@SchrodingersGat Ha! Just missed you by a couple hours. I believe all the stencils have been updated properly and that all footprints can be reviewed. KLC violations are about pad layer settings (which is intentional in this case) and the handsoldering variant of XQ using the normal XQ 3D model. Also OK.

There is still one outstanding issue (which I believe can wait for a later PR): The [datasheet](http://www.cree.com/led-components/media/documents/CLMVBFKA.pdf) listed for `Cree-PLCC4` doesn't show a footprint. I asked Cree for a recommended footprint and we'll see if/when they answer me.

**Comment by evanshultz** [comment]
Screenshot:
image

**Comment by SchrodingersGat** [comment]
thanks for your work on this

**Pull request merged**
