### PR TITLE
Create LED_RGB_5050-6.kicad_mod

### PR DESCRIPTION
**Pull request by JoanTheSpark**
regarding this forum post on KiCAD.info:
https://forum.kicad.info/t/smd-rgb-led-footprint-5050/653?u=joan_sparky

took PLCC-6 footprint as template for line thicknesses/etc.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi Joan,

Looks like all that needs to be done to meet KLC is to add a second RefDes to the Fab layer @ (0,0)

Cheers

**Comment by jkriege2** [comment]
Hi!

thanks for the contribution. I just had a look at it. Could you please change some things to conform to our KLC-libtrary standards and some measurement errors?

1. There should be a text-label `%R` on the F.Fab layer, typically centered in the symbol (i.e. at 0,0). You can make the font smaller to fit it inside. It serves as a second REFDES-label on F.Fab
2. According to the DS (http://dlnmh9ip6v2uc.cloudfront.net/datasheets/Components/LED/5060BRG4.pdf), the package is 5mm wide and 6mm height, but yours is only 5mm high. Please fix.
3. The courtyard clearance left and right is only 0.2mm, ut should be 0.25mm
4. the pads 1,2,3,4,5,6 should be at y=1.7mm, but yours are at y=2mm. Please fix.
5. Please add a 3D model link (even though the model does not yet exist, so it is used, when someone conributes or has a model). The link should be: `${KISYS3DMOD}/LEDs.3dshapes/LED_RGB_5050-6.wrl`
6. Finally please add a the datasheet URL to the description field

Best,
JAN

PS: Please (in future) ideally add a screenshot and a datasheet link to the PR, as this makes review easier/quicker. Also note that we have a continuous integration system now that checks for some KLC-violations in your symbols:
2017-05-12 07_32_23- 1 create led_rgb_5050-6 kicad_mod by joanthespark pull request 35 kicad_l

**Comment by JoanTheSpark** [comment]
Thx for the pointers and again sorry for the wild PR.. was my first.

**Comment by jkriege2** [comment]
Hi!

great work!

One last request, would you add a circle to F.Fab, indicating the window of the LED? This way the footprint is in line with e.g.
2017-05-12 22_29_22-library browser leds c__development_kicad_share_kicad_modules_leds pretty

Best,
JAN

**Comment by JoanTheSpark** [comment]
Done.

**Comment by jkriege2** [comment]
great work!
JAN

**Pull request merged**
