### PR TITLE
edit led 3mm and led 5mm

### PR DESCRIPTION
**Pull request by andres53016**
change the leds. But what it is to be done with 3d made by walter?

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hello @andres53016 could you please check this footprints using the [check_kicad_mod](https://github.com/KiCad/kicad-library-utils/tree/master/pcb) script?

**Comment by andres53016** [comment]
one question, Does the countyard must be square?

**Comment by CarlPoirier** [comment]
No you can make it round.

**Comment by ricardocrudo** [comment]
Hello @andres53016. The silkscreen are superposed to pads, please make them a little bit shorter. Also, check if everything is OK with the 3d models, including this your another pull request https://github.com/KiCad/kicad-library/pull/178.

**Pull request merged**
