### PR TITLE
added footprint for 1210(3225) RGB LED

### PR DESCRIPTION
**Pull request by hyOzd**
Datasheet: http://www.avagotech.com/docs/AV02-0610EN

### CODE REVIEW

**Comment by pointhi** [comment]
please check KLC:

```
6.2. Pad 1 is on the left first, then at the top, except at the top for PLCC (IPC-7351).
```

But more important, you define it as 1210 component, but I'm not sure if we should name it in this genric way, even the component is pretty close to the size of 1210 (but not exactly).

I would also propose to move the silk screen more to the pads. The silk screen should be fully visible after assembly, but you don't need to add a gap between component and silk screen. You could move for example the silk screen in y direction to 1.5mm.

**Comment by hyOzd** [comment]
I solved KLC 6.2, and moved silk screen closer.

I wasn't sure about the naming myself either. I used 1210 because this component was listed as 1210 in Digikey and Mouser. What do you think a more appropriate name would be?

**Comment by evanshultz** [comment]
@poeschlr Could you close and re-open?

@hyOzd Are you still willing to contribute? If so, please review the Travis output that will be coming from the above request and also post a screenshot of the footprint in a comment. Thank you!

**Comment by hyOzd** [comment]
led_rgb_1210

I also have a 3d model designed in freecad that looks like this. It doesn't look exactly like the one in the datasheet, but another one I had in my hand. Should I add it?

led_rgb_1210_3d

**Comment by poeschlr** [comment]
If it fits the footprint than by all means. (maybe include the datasheet for that component then.)

Now to review the footprint:
The documentation field should include more information than just the datasheet link
The keyword field might need some fixing. (why 3225 should it be 3227 or better 3.2x2.7mm?)
Fill out the 3d settings:
- path: ${KISYS3DMOD}/library_name.3dshapes/footprint_name.wrl
- scale: 1,1,1
- offset and rotation: 0,0,0

The pin 1 marker on fab should be only the chamfer (size 25% of package size ~0.7x0.7mm)
screenshot from 2017-06-24 10-54-08

**Comment by hyOzd** [comment]
Do I have to set scale to 1,1,1? Freecad models are in **mm**, but as you know kicad expects WRL models in inches. I will have to scale up the freecad model. In this case freecad file will have wrong dimensions. Can I just set scale to 0,39?

**Comment by poeschlr** [comment]
The wrl model should be scaled. If you use [kicad stepup](https://sourceforge.net/projects/kicadstepup/) this is done automatically.

**Comment by poeschlr** [comment]
By the way, to not use freecad 0.16 to export the step models. There is a bug in this version. Either use freecad 0.15 or one of the more recent 0.17 versions.
The step and wrl models should go into the [kicad-library](https://github.com/KiCad/kicad-library) repo and into the new [packages3d](https://github.com/KiCad/packages3D) repo.

**Comment by poeschlr** [comment]
@hyOzd could you fix the model scaling and the other suggestions such that we can finish this pull request?

**Comment by hyOzd** [comment]
@poeschlr I don't have time for fixing the 3d model at the moment. Can you accept the footprint without the 3d model?

**Comment by Shackmeister** [comment]
@hyOzd can you add the Fcstd file to the packages3d-source repo? Ill be happy to do the rest of the work from there

**Comment by poeschlr** [comment]
@hyOzd the model is not necessary for the footprint to be accepted. But the 3d settings of the footprint should be set correctly. (Such that the users can easily add their own model and we do not need to change the footprint if we get the model later on.)

And the pin 1 marker on fab needs to be fixed.

For more details see my earlier comment.

**Comment by hyOzd** [comment]
I fixed the chamfer. Isn't this okay?

rgb1210

**Comment by poeschlr** [comment]
The footprint looks really nice.

Please set the 3d model. Yes there might be an 3d model not found error but this way a user can add their own model.
(The error only comes up if you open the 3d settings dialog. Or in the 3d viewer. I think it is better the user is alerted why this footprint does not show up in the viewer than quietly simply not showing it.)
Also the KLC requires the 3d settings to be filled out.
(And i think @Shackmeister will export the model as soon as we are finished here.)

**Comment by Shackmeister** [comment]
@poeschlr do you have any comments before merging this?

**Comment by poeschlr** [comment]
Thanks at everyone involved here. (And sorry that it took me so long. I seem to have missed the latest commit.)

**Pull request merged**
