### PR TITLE
Added package outline for SMT LEDs

### PR DESCRIPTION
**Pull request by SchrodingersGat**
* Added F.Fab outline for LED_0402
* Added F.Fab outline for LED_0603
* Added F.Fab outline for LED_0805
* Added F.Fab outline for LED_1206

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
bump

**Comment by SchrodingersGat** [comment]
@ashtonchase @CarlPoirier @pointhi @diggit anyone want to tackle this? Improved LED_xxxx footprints by adding part outline to F.Fab layer

**Comment by pointhi** [comment]
thanks for the F.Fab layer.

I think we could add some more improvements to this footprints (in another PR):

* remove the inner silk screen, which shows a diode. It's not required and would likely only be a dot on a manufactured pcb
* the 3d model of ```LED_0402``` looks like it should be turned by 180 degree

**Comment by SchrodingersGat** [comment]
Check out https://github.com/KiCad/LEDs.pretty/pull/25

**Pull request merged**
