### PR TITLE
make leds modules klc compliant and add led 10mm

### PR DESCRIPTION
**Pull request by andres53016**

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Please add 3d model to LED-0805.
I think should be better make the silkscreen of SMD LEDs looks like the SMD diodes, please check out SOD-123 in Diodes_SMD lib.

**Comment by andres53016** [comment]
I made the changes you suggested me

**Comment by ricardocrudo** [comment]
merged with some addition in the LEDs SMD silkscreens. Thanks.

**Comment by andres53016** [comment]
Thanks Ricardo.

**Pull request merged**
