### PR TITLE
Add Osram LG T770

### PR DESCRIPTION
**Pull request by GyrosGeier**
This is a reverse mounted SMD LED.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @GyrosGeier thanks for your contribution. There are a few small things to change here:

* Make sure that the part attributes is set to "Normal + Insert" (this is required for SMD parts)
* Add the datasheet to the Doc field - http://www.osram-os.com/Graphics/XPic8/00088831_0.pdf/LG%20T770%20-%20TOPLED%20Reverse%20Gullwing.pdf
* Add some keywords to the Keywords field
* Add the LED_ prefix (LED_Osram_LG_T770)
* The part name must match the filename (replace the spaces in the name with _ character as per the filename)
* Reduce the width of the courtyard lines to 0.05mm (from 0.15mm)
* Add the outline of the LED package to the F.Fab layer (0.15mm width)
* Add polarization marks on the F.SilkS layer (check out how the polarity of the other LEDs is indicated)

e.g.

led

Thanks

**Comment by evanshultz** [comment]
@poeschlr Could you close and re-open?

@GyrosGeier Will you be able to fix the remaining issues so this PR can be merged?

**Comment by GyrosGeier** [comment]
Yes, made a note so I don't forget.

**Comment by poeschlr** [comment]
@GyrosGeier if you are still interested in contributing, please reopen the pull request over at the new repo. https://github.com/KiCad/kicad-footprints
This repo is declared legacy. (We do no longer accept pull requests here)

Sorry for the inconvenience.

**Pull request closed without merging**
