### PR TITLE
Led CREE-PLCC4 - fix Issue KiCad/kicad-library#1328

### PR DESCRIPTION
**Pull request by suzizecat**
Fixed issue KiCad/kicad-library#1328.
deleted the old footprint file because Git acted strange and i changed the name (caps letter)
@jkriege2 and @CountMurphy : Could you check if there's nothing wrong ? The DS isn't pretty clear about the footprint.

BTW The 3D model don't match anymore could @CountMurphy open an issue about that ?   

I'm based on this DS : http://www.cree.com/led-components/media/documents/CLMVBFKA.pdf

image

image

And the model (which isn't suited now...) 
image

### CODE REVIEW

**Comment by CountMurphy** [comment]
Far as I can tell this looks right. I'd also be happy to open a ticket about the 3D model, though I assume after this is merged in?

**Comment by suzizecat** [comment]
Well, you can start it right away if you want because the footprint don't need the 3D model. So, even if the model is broken, it's not a problem. Although the repos aren't the same, so no problems 😉 ,

**Comment by suzizecat** [comment]
@jkriege2 could you review review this when you'll find time ? Then you'll be able to close this PR and the issue at the same time ;)

**Comment by CountMurphy** [comment]
Cool, I can look into fixing the 3d model. Unfortunately I wont be able to really start on it for a week or two.

**Comment by suzizecat** [comment]
I just saw that there is a conflict with a newer pull request. Anyway, this push is still good, should i merge master into my branch ? (each time i have a conflict, i choose the wrong operation and screw up my PR 😢  )

The right operation should be to overwrite the master version.

**Comment by SchrodingersGat** [comment]
Merge kicad/master into this branch. You will be presented with the conflicts, and will have to solve them manually. Then, no more conflicts!

**Comment by SchrodingersGat** [comment]
We have all been stung by incorrect git operations at one point (or three)

**Comment by suzizecat** [comment]
Let's go for it !

**Comment by suzizecat** [comment]
Yay ! It worked !

**Comment by suzizecat** [comment]
Something is still messed up. Since there was a filename change, i'll look into that.

**Comment by suzizecat** [comment]
For an unknown my merge seems have gone bad... Before this drive me crazy, i think i'll open a new PR (but  i feel bad opening 2 PR for almost each request... )

**Comment by poeschlr** [comment]
Could you state your workflow on how you merge? Maybe we can help you find your mistake.

I'm not sure if i would be capable to merge something like this.
In some cases starting from a new branch might be the best solution. Just link this discussion in your new PR.

**Comment by suzizecat** [comment]
Well i'm using GitKraken.
I just merged master into my PR branch but got an error. Then i used the basic git command `git merge master` while being in my branch. I got a conflict (with my modification) which i resolved by keeping my copy.
But other files where changed...

Anyway, i just found a dirty trick which worked (create a new branch from master, apply changes, commit, hard reset my PR branch to master then fast forward to the new branch and push with overwrite 😗  )

**Comment by ppelleti** [comment]
Sorry, I didn't see this existing pull request when I created #46.  But that one has been merged now.

**Comment by poeschlr** [comment]
If this pull request is still required please reopen over at the new repo, as this repo is now declared as legacy and will no longer accept pull requests.

New repo: https://github.com/KiCad/kicad-footprints

Sorry for the inconvenience.

**Pull request closed without merging**
