### PR TITLE
Added 0605 (dual 0603) RGB LED. Common pad at pin 1

### PR DESCRIPTION
**Pull request by DavidMenting**
Added a footprint for tiny 1.6x1.5mm RGB LEDs like OPTOSUPPLY OSTB0603C1C-A or 
KINGBRIGHT ELECTRONIC KPTF-1616RGBC13.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@DavidMenting  if you're going off this datasheet here

http://www.farnell.com/datasheets/2046472.pdf

then I think you should increase the pad width to 0.85mm to accommodate the slightly larger version.

Also, PAD#2 is slightly wonky, it doesn't have the same X position as the others.

Also, the courtyard doesn't meet up at the corners.

Finally, I would also suggest going for a cleaner designation of PIN1, e.g. 

led

**Comment by SchrodingersGat** [comment]
Also please add the outline of the LED package to the F.Fab layer (line width = 0.15mm). Thanks

**Comment by evanshultz** [comment]
@poeschlr Could you close and re-open?

@DavidMenting Will you be able to fix the remaining issues so this PR can be merged?

**Comment by SchrodingersGat** [comment]
@DavidMenting I'm going to close this for now as you have not responded for quite some time. This can be re-opened if you can address the above concerns :)

**Pull request closed without merging**
