### PR TITLE
Rename LED-XP-G_CREE to LED_CREE-XP-G

### PR DESCRIPTION
**Pull request by evanshultz**
Use naming paradigm for all the rest of the LEDs. No changes other than footprint name.

### CODE REVIEW

**Comment by evanshultz** [comment]
Since this was an existing part, just renamed, can the Travis violations be ignored? This is a problem for all the CREE LED footprints in this repo (and maybe others).

**Comment by SchrodingersGat** [comment]
@evanshultz all that is missing is the second RefDes ;)

**Comment by SchrodingersGat** [comment]
Thanks!

**Comment by evanshultz** [comment]
Alright. Fixed. The other CREE ones aren't update, though. It sounds like I just volunteered myself...

**Pull request merged**
