### PR TITLE
Improve LED SMD footprints

### PR DESCRIPTION
**Pull request by descampsa**
Improve footprints of 0402, 0603, 0805 and 1206 LEDS.
Make the polarity markings visible (markings were too small and under the LED)
Also change pad sizes to metric, using dimensions from IPC-SM-782A.

### CODE REVIEW

**Comment by Schlumpf** [comment]
Hi @descampsa, is it correct, that you changed the description oft all files to 0603?

**Comment by SchrodingersGat** [comment]
And all the 3D models, too...

**Comment by descampsa** [comment]
Oops, yes, obviously this is an error, not sure how it happened, i remember checking that.
I will fix that this evening.
Apart for part, do you think it is good?

Pad sizes from IPC-SM-782A are slightly bigger than what manufacters usually recommend, but i don't think it should be a problem (with my limited experience). What standard/reference do you usually use (if any)?

The new polarity marking takes more place than i would like, but at least it is unambiguous (and readable). A more compact alternative could be the IPC-7351C markings (see [here](http://cskl.de/fileadmin/downloads/PCBLIBRARIES/Documentation/What-is-New-in-IPC-7351C_.pdf), pages 18 and 20). I can add a version with those markings if you want.

**Comment by descampsa** [comment]
The fact that the marking is covered by the soldered LED is only one part of the problem. 
With small footprints, it is simply impossible to print a readable diode symbol between the pads.
You can see the result for a 0603 on a board made by seeedstudio in attachment. Maybe better fab could produce something better, but i doubt it is possible to get something readable by bare eye at this size.

However, i agree that the marking probably take too much space, i can make it smaller, but they will always take a significant amount of space if we want them to be readable. 
The IPC symbol is maybe the best solution, readable and don't take much space, but maybe more ambiguous  (not sure how well known it is?).
Any feedback is welcome.

led

**Comment by diggit** [comment]
Polarity marking definitely should not be under package. It can cause problems during assembly and/or testing. IPC primary marking style is compact and easy. I'd choose that.

**Comment by descampsa** [comment]
Ok, since IPC looks like the best option, i have changed it to the default marking, and removed the old marking version.
Also fixed PLCC 2835 for IPC.

If this is accepted, i will do the same for the diode library.

**Comment by SchrodingersGat** [comment]
Hi @descampsa this is a great improvement to these symbols. If you have the time to address the diodes in a similar fashion that would be great. The IPC polarity markers are very clean and succinct.

**Pull request merged**
