### PR TITLE
Added footprints for CREE XHP50 and XHP70

### PR DESCRIPTION
**Pull request by SchrodingersGat**
**Variants**
- 6V version
- 12V version

**Datasheets**
- http://www.cree.com/~/media/Files/Cree/LED%20Components%20and%20Modules/XLamp/Data%20and%20Binning/ds%20XHP70.pdf
- http://www.cree.com/~/media/Files/Cree/LED%20Components%20and%20Modules/XLamp/Data%20and%20Binning/ds%20XHP50.pdf

**Notes**
- Stencil pattern designed to match datashet
- 6V and 12V variant uses the same part, with a different footprint (as per datasheet spec)

**12V Version**
12v

**6V Version**
6v

pcb

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Added CREE-XP footprint

xp

**Comment by SchrodingersGat** [comment]
This PR now contains a lot of LED footprints from CREE

**Comment by SchrodingersGat** [comment]
@ashtonchase  @pointhi  either of you guys want to take a look at these ones?

**Comment by SchrodingersGat** [comment]
bump

**Comment by pointhi** [comment]
```
checking module: LED_CREE-XHP50_12V
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
checking module: LED_CREE-XHP50_6V
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
```

**Comment by SchrodingersGat** [comment]
Hi @pointhi the two footprints are different configurations of exactly the same LED and so I don't see the point of duplicating the 3D model. I think it makes sense that they both point to the same file in this case.

**Comment by SchrodingersGat** [comment]
@jkriege2 want to work your magic on this one? 

( btw I should have some time soon\* to have a look through all your PRs, been super busy of late )

**Comment by jkriege2** [comment]
Hi!

only one question: You have a "handSoldering" symbol only for XQ, what about the others: Aren't they hand-solderable?

Otherwise I would merge this ...

Best,
JAN

**Comment by jkriege2** [comment]
I quickly drew up some symbols for such LEDs (with pad and in series with/without pad, see here:
https://github.com/KiCad/kicad-library/pull/809

... but I think we should create an additional library `leds.lib/.dcm`, which assembles special LEDs, like the parallel 6V and series 12V-version with their additional count-directed diodes. See e.g. p. 32/top in http://www.cree.com/~/media/Files/Cree/LED%20Components%20and%20Modules/XLamp/Data%20and%20Binning/ds%20XHP50.pdf

Best,
JAN

**Comment by jkriege2** [comment]
Hi!

I also started that leds.lib-file

cu
JAN

**Comment by SchrodingersGat** [comment]
I think we should merge the ones made already and add hand-soldering versions if wanted in the future?

**Comment by jkriege2** [comment]
OK! Nice Work BTW,

JAN

**Pull request merged**
