### PR TITLE
Added footprint for "1W/3W LED"

### PR DESCRIPTION
**Pull request by MartinStej**
Footprint is based on following
 datasheet: https://www.gme.cz/data/attachments/dsh.518-234.1.pdf
Package name seems to be "1W" or "3W" LED.
3D model pull request was send to "KiCad/kicad-library"

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @MartinStej thanks for contributing

First off, we have some [python scripts](https://github.com/KiCad/kicad-library-utils) that can be used to help show where a footprint does meet [KLC requirements](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention).

There are also some specific things to address here:

### Change Reference Field

The reference field should contain default value of `REF**` (not `L**`). Please change this back to default!

### Pin-1 On Left

For diode, pin-1 should be on the left. This can be achieved simply by rotating the part.

### Add Fabrication Layer
The mechanical outline of the part should be drawn on the Fabrication layer (*most* of the footprints in this library conform to this but some are out of date).

### Add polarization symbol
The fab layer should also show the diode polarity (see how this is handled for the other diodes)

### Silkscreen layer
Silkscreen should be entirely visible once the component is placed on the PCB (no silkscreen under part).

### Surface Mount
This footprint should be designated as "Surface Mount" in the footprint properties window.

In older versions of Kicad this will be called "Normal + Insert", in the most recent version it will say "Surface Mount"

**Comment by MartinStej** [comment]
Hi @SchrodingersGat,
 thanks for pointing on mistakes. Actually I'm kinda new in KiCad, so I appreciate your help. I'll try to fix all the problems and then I'll push new commit.
 Thanks

**Comment by MartinStej** [comment]
Hi @SchrodingersGat,
 updated, but I still have problem with rule "6.6" and frankly speaking, I do not know what this rule means.
 Also there are minor problems with rule 10.5 and 10.8, but actually I think it is not problem in this case.
Thanks

**Comment by SchrodingersGat** [comment]
Thanks, great updates :)

Rule 6.6 relates to the placement of a courtyard line. This is a guide for how close other components can be placed to the footprint.

Courtyard clearance should be set to 0.25mm

e.g.

crtyd

also two other things:

1. Please add diode polarity symbol to the F.Fab layer
2. Please add a copy of the RefDes to the F.Fab layer. To achieve this, add a text item with the text `%R`

capture

**Comment by MartinStej** [comment]
Thanks for great support!
Since my national language is not English, I really did not know what "courtyard" means in term of PCB. Thanks for explanation.
Regarding to 3D model, I already sent pull request to "KiCad/kicad-library", but no response yet.

**Comment by SchrodingersGat** [comment]
I have seen the 3D model PR, I shall wait until this one is merged until dealing with that! :) I do not have time right now to look at your latest update to this footprint but I will look soon. 

Regards

**Comment by SchrodingersGat** [comment]
Looks great!

**Pull request merged**
