### PR TITLE
Set anode pins as square.  Reduce pad sizes slightly.

### PR DESCRIPTION
**Pull request by DavidGriffith**
The anode pins for these two-pin through-hole LEDs were round instead of square -- and the cathodes were square instead of round.  Also slightly reduced the pad sizes to more easily allow a trace at .250mm to go between them.

### CODE REVIEW

**Comment by ricardocrudo** [comment]
I believe cathode is supposed to be the square one, since it's pin 1.

**Comment by CarlPoirier** [comment]
Indeed. KiCad sticks to the IPC standard when it comes to diode polarity.

**Comment by DavidGriffith** [comment]
What alternate world have I been in where the anode of LEDs was always square?

**Comment by jkriege2** [comment]
can this be closed?

**Comment by SchrodingersGat** [comment]
Closing - as discussed the assumption here is incorrect :)

**Pull request closed without merging**
