### PR TITLE
Add 2835 LED footprint

### PR DESCRIPTION
**Pull request by yaqwsx**
This footprints follows this datasheet: http://www.everlight.com/file/ProductFile/67-21S-KK2C-H4040QAR32835Z15-2T.pdf

Also PR for 3D model into kicad-library was opened.

### CODE REVIEW

**Comment by yaqwsx** [comment]
3D model PR: https://github.com/KiCad/kicad-library/pull/452

**Comment by SchrodingersGat** [comment]
@yaqwsx a few suggestions to help this towards merging:

a) The silkscreen markings on the side should indicate polarisation by being closer to the + terminal (look at how LED_0603 | LED_0806 |  LED_1206 does this)

b) Move the part name and REF** out from the part a little bit

c) Pad size is outside stated tolerance

Thanks

**Comment by yaqwsx** [comment]
@SchrodingersGat Hi, I modified the part according to your notes, however I kept the pads larger than datasheet recommends. I have made several boards with recommended pad sizes and it caused troubles during soldering (both hand and reflow -- part misaligned itself). Making them wider by 0.1 mm helps.

**Comment by SchrodingersGat** [comment]
Ok good work on the polarizing marks, I'm happy with slightly larger pads if you have verified them in-use. 

One last thing - we're trying to keep mechanical outlines on the Fab layers (e.g. https://github.com/KiCad/Crystals.pretty/pull/5) so please move LED outlines from Drawing to Fab layer :)

Thanks!

**Comment by yaqwsx** [comment]
Ok, I changed the layer of drawing. I also included handsolder version of the package based on a feedback I received

**Comment by SchrodingersGat** [comment]
Just change "_Handsolder" to "_Handsoldering" and we are good to go :)

**Comment by yaqwsx** [comment]
Done

**Comment by SchrodingersGat** [comment]
Almost there - I now notice that the footprint isn't centred horizontally - the F.Fab outline layer indicates that the left side is at -1.73mm but the right side is at +1.77mm (they should be ±1.75mm).

Boot footprints are also violating rule 6.4 - https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention but this may not be hard to meet with non-symmetrical pads.

**Comment by yaqwsx** [comment]
I finally make time for adjusting the changes. I have centered the F.Fab layer. By violating rule 6.4 you mean that center should be placed in the middle of clear space between pads? This seem weird to me.

**Comment by SchrodingersGat** [comment]
@yaqwsx yes it would be weird to center the clear space - the way that you have done it here makes sense to me.

One thing left - I was a bit confused because you have pin-1 on the right whereas other LEDs in the library have pin-1 on the left. If you look at the silkscreen on the other LEDs (e.g. LED_0805) you will notice that the silkscreen markings are biased towards pin 1.

I told you to put them towards pin 2 but this was incorrect. 

* Align silkscreen with pin 1

led

Also:

* Move text LED_PLCC_2835 up slightly as shown
* Reduce F.Fab lines to 0.05mm width

(And same changes for the Handsoldering part :)

Thanks!

**Comment by SchrodingersGat** [comment]
Once you have made these changes, it would be good to rotate the parts 180 degrees around the origin such that pin 1 is on the left, so that they match all the other LED footprints.

**Comment by PopeLevi** [comment]
Plz merge <3

**Comment by SchrodingersGat** [comment]
@PopeLevi  if you make the last few changes as noted above, I'll merge <3

**Comment by SchrodingersGat** [comment]
* Rotate the part 180 degrees so that pin-1 is on the left
* Adjust the silkscreen so that it is aligned with pin 1 (see my picture above).

*Note: I previously instructed you to align the silkscreen with Pin2 but I was wrong. The shame is mine*

**Comment by yaqwsx** [comment]
I am sorry for the delay, however there were many higher-priority tasks. I changed the line thickness, fixed the silkcreen and rotated both parts.

**Comment by SchrodingersGat** [comment]
Thanks, good work :)

**Pull request merged**
